//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class NVRAccessSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static NVRAccessSetting defaultInstance = ((NVRAccessSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NVRAccessSetting())));
        
        public static NVRAccessSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtsp://")]
        public string RTSP_HEADER {
            get {
                return ((string)(this["RTSP_HEADER"]));
            }
            set {
                this["RTSP_HEADER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.124")]
        public string NVR_IP {
            get {
                return ((string)(this["NVR_IP"]));
            }
            set {
                this["NVR_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string NVR_USER_NAME {
            get {
                return ((string)(this["NVR_USER_NAME"]));
            }
            set {
                this["NVR_USER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tjxldnpdj2018!")]
        public string NVR_USER_PW {
            get {
                return ((string)(this["NVR_USER_PW"]));
            }
            set {
                this["NVR_USER_PW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://")]
        public string HTTP_HEADER {
            get {
                return ((string)(this["HTTP_HEADER"]));
            }
            set {
                this["HTTP_HEADER"] = value;
            }
        }
    }
}
